#!/bin/bash

idx=0
ps -a | grep a.out | while read line
do
    echo $line
    pid=$(echo "$line" | cut -d' ' -f1)
    echo "PID : $pid"
    kill_cmd="kill -15 $pid"
    echo "[$idx] $kill_cmd"
    $kill_cmd || echo ignore_error
    sleep 1
    idx=$((idx+1))
done
